const CREATE_RAZORPAY_ORDER_REQUESTED = 'createRazorpayOrderRequested';
const CREATE_RAZORPAY_ORDER_SUCCEEDED = 'createRazorpayOrderSucceeded';
const CREATE_RAZORPAY_ORDER_FAILED = 'createRazorpayOrderFailed';
const CREATE_RAZORPAY_ORDER_RESET = 'createRazorpayOrderReset';

const CREATE_PAYMENT_REQUESTED = 'createPaymentRequested';
const CREATE_PAYMENT_SUCCEEDED = 'createPaymentSucceeded';
const CREATE_PAYMENT_FAILED = 'createPaymentFailed';
const CREATE_PAYMENT_RESET = 'createPaymentReset';

export default {
  CREATE_RAZORPAY_ORDER_REQUESTED,
  CREATE_RAZORPAY_ORDER_SUCCEEDED,
  CREATE_RAZORPAY_ORDER_FAILED,
  CREATE_RAZORPAY_ORDER_RESET,
  CREATE_PAYMENT_REQUESTED,
  CREATE_PAYMENT_SUCCEEDED,
  CREATE_PAYMENT_FAILED,
  CREATE_PAYMENT_RESET
};
