const RENTALS_REQUESTED = 'rentalsRequested';
const RENTALS_SUCCEEDED = 'rentalsSucceeded';
const RENTALS_FAILED = 'rentalsFailed';

const CREATE_RENTAL_REQUESTED = 'createRentalRequested';
const CREATE_RENTAL_SUCCEEDED = 'createRentalSucceeded';
const CREATE_RENTAL_FAILED = 'createRentalFailed';
const CREATE_RENTAL_RESET = 'createRentalReset';

const RENTAL_DETAILS_REQUESTED = 'rentalDetailsRequested';
const RENTAL_DETAILS_SUCCEEDED = 'rentalDetailsSucceeded';
const RENTAL_DETAILS_FAILED = 'rentalDetailFailed';

const COMPLETE_RENTAL_REQUESTED = 'completeRentalRequested';
const COMPLETE_RENTAL_SUCCEEDED = 'completeRentalSucceeded';
const COMPLETE_RENTAL_FAILED = 'completeRentalFailed';
const COMPLETE_RENTAL_RESET = 'completeRentalReset';

export default {
  RENTALS_REQUESTED,
  RENTALS_SUCCEEDED,
  RENTALS_FAILED,
  CREATE_RENTAL_REQUESTED,
  CREATE_RENTAL_SUCCEEDED,
  CREATE_RENTAL_FAILED,
  CREATE_RENTAL_RESET,
  RENTAL_DETAILS_REQUESTED,
  RENTAL_DETAILS_SUCCEEDED,
  RENTAL_DETAILS_FAILED,
  COMPLETE_RENTAL_REQUESTED,
  COMPLETE_RENTAL_SUCCEEDED,
  COMPLETE_RENTAL_FAILED,
  COMPLETE_RENTAL_RESET,
};
